# Generated by Django 4.1.1 on 2023-05-12 15:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseDetail',
            fields=[
                ('cid', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentDetail',
            fields=[
                ('did', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dname', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='FacultyDetail',
            fields=[
                ('fid', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='StudentDetail',
            fields=[
                ('sid', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('sub_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_name', models.TextField(max_length=500)),
                ('cid_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartmate__1.coursedetail')),
                ('did_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartmate__1.departmentdetail')),
                ('fid_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartmate__1.facultydetail')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('note_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_text', models.TextField(max_length=500)),
                ('file', models.FileField(max_length=300, null=True, upload_to='notes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('fid_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartmate__1.facultydetail')),
                ('sub_id_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartmate__1.subject')),
            ],
        ),
        migrations.AddField(
            model_name='coursedetail',
            name='did_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartmate__1.departmentdetail'),
        ),
    ]
