# Generated by Django 4.1.1 on 2023-05-13 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartmate__1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultydetail',
            name='did_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='smartmate__1.departmentdetail'),
        ),
        migrations.AddField(
            model_name='studentdetail',
            name='cid_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='smartmate__1.coursedetail'),
        ),
        migrations.AlterField(
            model_name='facultydetail',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
