# Generated by Django 4.1.1 on 2023-05-19 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartmate__1', '0003_note_cid_fk_studentdetail_access_stu_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('card_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('set_title', models.TextField(max_length=100)),
                ('term', models.TextField(max_length=100)),
                ('desc', models.TextField(max_length=100)),
                ('cid_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='smartmate__1.coursedetail')),
                ('sid_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartmate__1.studentdetail')),
                ('sub_id_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartmate__1.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('ann_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(max_length=100)),
                ('desc', models.TextField(max_length=500)),
                ('date', models.DateTimeField(auto_now=True)),
                ('cid_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='smartmate__1.coursedetail')),
                ('fid_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartmate__1.facultydetail')),
                ('sub_id_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartmate__1.subject')),
            ],
        ),
    ]
