# Generated by Django 4.1.1 on 2023-06-08 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartmate__1', '0004_flashcard_announcement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('forum_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='anonymous', max_length=200)),
                ('topic', models.CharField(max_length=300)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(default='anonymous', max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='access_stu',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='cid_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartmate__1.coursedetail'),
        ),
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('dis_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('discuss', models.CharField(max_length=1000)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(default='anonymous', max_length=200, null=True)),
                ('forum', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='smartmate__1.forum')),
            ],
        ),
    ]
